### PR TITLE
Improves code quality - PSRs

### PR DESCRIPTION
**Pull request by gabrieljmj**
Nowdays is important have a code "readable" for all comunity and for it was created php-fig.org. What I did in this PR was improve the code quality following the PSRs and setting code problems.

### CODE REVIEW

**Comment by iagomelanias** [comment]
+1

**Comment by guilhermegonzaga** [comment]
+1

**Comment by reinaldorauch** [comment]
+1

**Comment by matheusfavieira** [comment]
+1

**Comment by ricardotulio** [comment]
The V2 has been deprecated since the release of V3 and this issue will be resolved in the V3.

**Pull request closed without merging**
